// <auto-generated />
using System;
using LoyaltyRewards.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoyaltyRewards.Migrations
{
    [DbContext(typeof(LoyaltyRewardsDbContext))]
    partial class LoyaltyRewardsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoyaltyRewards.Models.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfActiveOffers")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LoyaltyRewards.Models.Offer", b =>
                {
                    b.Property<Guid>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateExpiring")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MemberAssignedMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OfferId");

                    b.HasIndex("MemberAssignedMemberId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("LoyaltyRewards.Models.OfferType", b =>
                {
                    b.Property<Guid>("OfferTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysValid")
                        .HasColumnType("int");

                    b.Property<int>("ExpirationType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferTypeId");

                    b.ToTable("OfferTypes");
                });

            modelBuilder.Entity("LoyaltyRewards.Models.Offer", b =>
                {
                    b.HasOne("LoyaltyRewards.Models.Member", "MemberAssigned")
                        .WithMany("AssignedOffers")
                        .HasForeignKey("MemberAssignedMemberId");

                    b.Navigation("MemberAssigned");
                });

            modelBuilder.Entity("LoyaltyRewards.Models.Member", b =>
                {
                    b.Navigation("AssignedOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
